spring:
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false

  h2:
    console:
      enabled: true
      path: /h2-console