DROP TABLE IF EXISTS employee;

CREATE TABLE employee (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  OFFICE VARCHAR(4) NOT NULL,
  EMAIL VARCHAR(150) NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  ROLE VARCHAR(150) NOT NULL
);

INSERT INTO employee (NAME, OFFICE, EMAIL, PHONE, ROLE)
VALUES("HUGO ", "100A", "address@email.com", "2323239911", "supervisor");
